<a href="https://colab.research.google.com/github/Mamadou8bah/BlogAPI/blob/main/ReviewPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Programming Tutorial

- Welcome to this comprehensive Python tutorial! This Jupyter Notebook is designed to help you learn Python programming from the ground up.
- Each section includes explanations, code examples, and exercises to reinforce your understanding. Let's dive in!

---

## Introduction to Python Programming


- **Python** is a high-level, interpreted programming language.
- Known for its **simplicity** and **readability**.
- Created by **Guido van Rossum** and first released in 1991.
- Emphasizes code readability with significant indentation.

### Why Learn Python?

- **Easy to Learn**: Simple syntax ideal for beginners.
- **Learning Curve** : Python is generally considered to be easier to learn and
use than C, due to its simpler syntax, automatic memory management,
and built-in data structures. C requires a deeper understanding of
computer architecture and low-level programming concepts, making it
more difficult to learn and master.
- **Versatile**: Used in web development, data analysis, AI, automation, etc.
- **Strong Community**: Extensive libraries and community support.
- **High Demand**: Valuable skill with numerous career opportunities.

### Key Features

- **Interpreted Language**: Executes code line by line.
- **Cross-Platform**: Runs on Windows, macOS, Linux.
- **Rich Standard Library**: Extensive modules for various tasks.
- **Multiple Paradigms**: Supports procedural, object-oriented, and functional programming.
- **Dynamic Typing**: Variables are typed at runtime.

### Real-World Applications

- **Web Development**: Django, Flask.
- **Data Science**: Pandas, NumPy, Matplotlib.
- **Machine Learning**: TensorFlow, Scikit-learn.
- **Automation**: Scripting and automating tasks.
- **Game Development**: Pygame.

### Setting Up Python

#### 1. Install Python

- Download from [python.org/downloads](https://www.python.org/downloads/).
- For Windows, check **"Add Python to PATH"** during installation.

#### 2. Verify Installation

```bash
python --version
```

#### 3. Install Essential Tools

- **pip**: Package manager (pre-installed with Python 3.4+).
- **Virtual Environments**:

  ```bash
  python -m venv myenv
  ```

- **Jupyter Notebook**:

  ```bash
  pip install notebook
  ```

#### 4. Choose a Code Editor or IDE

- **Beginner-Friendly**: IDLE, Visual Studio Code.
- **Advanced**: PyCharm.

### Running Python Code

#### Interactive Shell

- Start by typing `python` in the terminal.
- Execute code line by line.

#### Script Files

- Write code in a file with a `.py` extension.
- Run with:

  ```bash
  python script_name.py
  ```

#### Jupyter Notebooks

- Launch with `jupyter notebook`.
- Interactive web interface for code execution.

#### Integrated Development Environments (IDEs)

- Use tools like PyCharm or VS Code for enhanced features.


---

---

<a id="2"></a>
##  Python Syntax

Python syntax is clean and easy to understand. Here's a simple "Hello, World!" example:

In [ ]:
print("Hello World")

Hello World

---

<a id="3"></a>
## 3. Python Comments

Comments are used to explain code and are ignored by the interpreter.

- **Single-line comment**:

In [ ]:
# This is a comment

- **Multi-line comment**:

In [ ]:
"""
This is a
multi-line comment
"""



<a id="4"></a>
##  Python Variables

-Variables in Python are used to store data values that can be referenced and manipulated throughout your program.
- They act as containers for data and are fundamental to programming in Python.


### Variable Assignment
 - Assigning a Value: You assign a value to a variable using the equals sign =.

In [ ]:


x = 10
name = "Baboucarr"
print(x)

10

<strong>Dynamic Typing </strong>: Python is dynamically typed, meaning you don't declare the type of variable. The type is inferred from the value assigned.

In [ ]:
x = 5          # x is an integer
x = "Hello"    # Now x is a string

#### Variable Naming Rules
**Start with a Letter or Underscore:** Variable names must begin with a letter (a–z, A–Z) or an underscore _.

**Letters, Numbers, and Underscores:** The rest of the variable name can include letters, numbers, or underscores.

**Case Sensitive:** age, Age, and AGE are different variables.

**Cannot Use Reserved Keywords:** Avoid using Python's reserved words like if, else, class, etc.

In [ ]:
# Valid names
user_name = "Bob"
_counter = 1
total3 = 100

# Invalid names
3total = 100     # Cannot start with a number
user-name = "Bob"  # Hyphens are not allowed
class = "Math"     # 'class' is a reserved keyword
print(user-name)

SyntaxError: invalid decimal literal (3321103210.py, line 7)

### Data Types
Variables can store data of various types:

**Numeric Types:** `int`, `float`, `complex`

In [ ]:
age = 25          # Integer
price = 19.99     # Float
z = 2 + 3j        # Complex number
print(type(z))

<class 'complex'>

In [ ]:
String: Text enclosed in quotes
Strings are arrays of Unicode characters.

---

<a id="5"></a>
## 5. Python Data Types

Common data types in Python include:

- **Numeric Types**: `int`, `float`, `complex`
- **Text Type**: `str`
- **Sequence Types**: `list`, `tuple`, `range`
- **Mapping Type**: `dict`
- **Set Types**: `set`, `frozenset`
- **Boolean Type**: `bool`

---

<a id="7"></a>
## 7. Python Casting

Casting is used to convert data types.

In [ ]:
x = int(1)        # x will be 1
y = float("3.5")  # y will be 3.5
z = str(5)        # z will be '5'
y

3.5

---

<a id="8"></a>
## 8. Python Strings

Strings are arrays of Unicode characters.

Syntax

slice = s[start:stop:step]

start: index to begin (inclusive). Default = start of string.

stop: index to end (exclusive). Default = end of string.

step: stride (can be negative). Default = 1.

Index:  0 1 2 3 4 5 6 7 8 9 10 11 12
Chars:  H e l l o ,   W o r  l  d  !
Neg:   -13           -6 -5 -4 -3 -2 -1

In [ ]:
s = "Hello, World!"
print(s[0])     # Output: H
print(s[-1])
print(s[7:12])  # Output: World Slicing

H
!
World

### String Methods

In [ ]:
print(s.lower())            # hello, world!
print(s.upper())            # HELLO, WORLD!
print(s.replace("H", "J"))  # Jello, World!
s.title()       # 'Hello, World!'
s.swapcase()    # 'hELLO, wORLD!'

#### Concatenation and repetition:

In [ ]:
string1 = 'Hello, World!'
string2 = "Python is awesome"
concatenated = string1 + " " + string2  # 'Hello, World! Python is awesome'
repeated = string1 * 3  # 'Hello, World!Hello, World!Hello, World!'

length = len(string1)
words = string2.split()  # ['Python', 'is', 'awesome']
joined = ' '.join(words)  # 'Python is awesome'

#### Checking substrings:

In [ ]:
contains = 'Python' in string2  # True
not_contains = 'Java' not in string2  # True

#### Using f-strings (Python 3.6+)
An **f-string** is a Python string literal prefixed with `f` that lets you directly embed expressions inside `{}` for fast, readable string formatting.

In [ ]:
name = "Lamin"
age =26
f_intro = f"My name is {name} and I am {age} years old"

In [ ]:
f_intro

'My name is Lamin and I am 26 years old'

#### String Immutability
- In Python, strings are immutable, meaning once a string is created, it cannot be changed. Any modification creates a new string.

In [ ]:
my_string = "Hello"
# Attempting to change the first character
my_string[0] = 'h'  # This will raise a TypeError because strings are immutable
my_string

TypeError: 'str' object does not support item assignment

In [ ]:
# If you want to change part of a string, you need to create a new string:

my_string = "Hello"
# To change the first character, we create a new string
new_string = 'h' + my_string[1:]  # 'hello'

---

<a id="9"></a>
## 9. Python Booleans

Booleans represent one of two values: `True` or `False`.

In [ ]:
print(10 > 9)     # Output: True
print(10 == 9)    # Output: False

True
False

These are built-in constants in Python and are case-sensitive (True and False, not true and false)

#### Boolean Operators

- and: Returns True if both operands are True.
- or: Returns True if at least one operand is True.
- not: Inverts the boolean value.

In [ ]:
# Examples:
True and False  # False
True or False   # True
not True        # False

False

#### Short-Circuit Evaluation:
- `and`: If the first operand is `False`, the second operand is not evaluated.
- `or`: If the first operand is `True`, the second operand is not evaluated.

#### Comparison Operators:
- Equal to: ==
- Not equal to: !=
- Greater than: >
- Less than: <
- Greater than or equal to: >=
- Less than or equal to: <=

In [ ]:
# Examples:
5 == 5        # True
3 != 2        # True
4 > 2         # True
3 < 1         # False
5 >= 5        # True
2 <= 1        # False

#### Boolean Expressions in Control Flow:

if Statements:

#### Syntax and Indentation
**Indentation:** Python uses indentation (spaces or tabs) to define code blocks. Consistent indentation is crucial.

In [ ]:
if condition:
    # Indented code block
    execute_this()

Colons (:): A colon is used at the end of the if, elif, and else statements.

In [ ]:
age = 18
if age >= 18:
    print("You are an adult.")
else:
    print("You are a minor.")
# Output: You are an adult.

You are an adult.

In [ ]:
if (x > 0) and (x < 10):
    print("x is between 1 and 9.")

if (user == 'admin') or (user == 'superuser'):
    print("Access granted.")

if not logged_in:
    print("Please log in.")

### Conditional Expressions (Ternary Operator)
- Python supports conditional expressions for concise conditional assignments.

In [ ]:
age = 20
status = "Adult" if age >= 18 else "Minor"
print(status)

Adult

---

## Python Lists

A **list** is an **ordered**, **mutable** (changeable) collection that can hold items of any type, including mixed types and duplicates.

### Key Points
- **Indexed and sliceable**: `lst[0]`, `lst[1:3]`
- **Allows duplicates**
- **Dynamic size**: you can `append()` or `remove()` items
- **Iterable**: can be looped over with `for`

In [ ]:
# Empty list
empty_list = []

# List of integers
numbers = [1, 2, 3, 4, 5]

# List of strings
fruits = ['apple', 'banana', 'cherry']

# Mixed data types
mixed_list = [1, 'hello', 3.14, True]

# List of lists (nested list)
matrix = [[1, 2], [3, 4]]

#### Accessing List Elements
List elements are indexed starting from 0. Negative indices start from -1 (last element).

In [ ]:
fruits = ['apple', 'banana', 'cherry']

# Accessing elements by index
first_fruit = fruits[0]   # 'apple'
second_fruit = fruits[1]  # 'banana'

# Negative indexing
last_fruit = fruits[-1]   # 'cherry'
second_last = fruits[-2]  # 'banana'

# Accessing elements in a nested list
matrix = [[1, 2],
          [3, 4]]
element = matrix[0][1]    # 2

### Slicing Lists
- SLicing allows you to get a subset of a list

In [ ]:
numbers = [1, 2, 3, 4, 5, 6]

# Syntax: list[start:stop:step]
subset = numbers[1:4]      # [2, 3, 4]
first_three = numbers[:3]  # [1, 2, 3]
from_four = numbers[3:]    # [4, 5, 6]
every_other = numbers[::2] # [1, 3, 5]
reversed_list = numbers[::-1]  # [6, 5, 4, 3, 2, 1]

#### Modifying Lists
Lists are mutable, meaning their contents can be changed after creation.
#### Changing Elements

In [ ]:
numbers = [10, 20, 30]
numbers[1] = 25  # [10, 25, 30]

#### Adding Elements
  - append(item): Adds an item to the end of the list

In [ ]:
numbers = [1, 2, 3]
numbers.append(4)  # [1, 2, 3, 4]

# insert(index, item): Inserts an item at a specified index.
numbers.insert(1, 1.5)  # [1, 1.5, 2, 3, 4]

#remove(item): Removes the first occurrence of an item.
numbers.remove(1.5)  # [1, 2, 3, 4, 5, 6, 7, 8]
# pop(index): Removes and returns the item at the given index. If index is omitted, removes the last item.
last_item = numbers.pop()    # 8
specific_item = numbers.pop(0)  # 1
# clear(): Removes all items from the list.
numbers.clear()  # []

## List Operations
Concatenation (+): Combines two lists.

In [ ]:
list1 = [1, 2]
list2 = [3, 4]
combined = list1 + list2  # [1, 2, 3, 4]
combined

[1, 2, 3, 4]

In [ ]:
# Repetition (*): Repeats a list multiple times.

zeros = [0] * 5  # [0, 0, 0, 0, 0]
zeros

[0, 0, 0, 0, 0]

### Iterating Over Lists
You can iterate over lists using loops.

In [ ]:
fruits = ['apple', 'banana', 'cherry']

# Using a for loop
for fruit in fruits:
    print(fruit)

# Using indices
for i in range(len(fruits)):
    print(fruits[i])

# Using enumerate to get index and value
for index, fruit in enumerate(fruits):
    print(index, fruit)

apple
banana
cherry
apple
banana
cherry
0 apple
1 banana
2 cherry

###  Sorting Lists
`sort()`: Sorts the list in place.

In [ ]:
numbers = [5, 2, 9, 1]
numbers.sort()  # [1, 2, 5, 9]
numbers.sort(reverse=True)  # [9, 5, 2, 1]
# Custom sort
words = ['apple', 'banana', 'cherry']
words.sort(key=len)  # ['apple', 'banana', 'cherry'] (sorted by length)

#sorted(iterable): Returns a new sorted list without modifying the original.
numbers = [3, 1, 4, 1, 5]
sorted_numbers = sorted(numbers)  # [1, 1, 3, 4, 5]

### Nested Lists (2D Lists)

In [ ]:
# 2D list (matrix)
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Accessing elements
element = matrix[1][2]  # 6

# Iterating over a 2D list
for row in matrix:
    for item in row:
        print(item, end=' ')
    print()

---

<a id="12"></a>
## 12. Python Tuples

- In Python, a tuple is an immutable, ordered sequence of elements.
- Tuples are similar to lists, but unlike lists, they cannot be changed after they are created.

### Creating Tuples

In [ ]:
# Empty tuple
empty_tuple = ()

# Tuple of integers
numbers = (1, 2, 3)

# Tuple of strings
fruits = ('apple', 'banana', 'cherry')

# Mixed data types
mixed_tuple = (1, 'hello', 3.14, True)

# Nested tuple
nested_tuple = (1, (2, 3), [4, 5])

# Tuple without parentheses (tuple packing)
implicit_tuple = 1, 2, 3

**Note:** A single element tuple requires a comma after the element.

In [ ]:
single_element_tuple = (5,)  # Correct
not_a_tuple = (5)            # This is just the integer 5, not a tuple

#### Accessing Tuple Elements
- Elements in a tuple can be accessed using indices, similar to lists.

In [ ]:
fruits = ('apple', 'banana', 'cherry')

# Accessing elements by index
first_fruit = fruits[0]     # 'apple'
second_fruit = fruits[1]    # 'banana'

# Negative indexing
last_fruit = fruits[-1]     # 'cherry'
second_last = fruits[-2]    # 'banana'

# Accessing elements in a nested tuple
nested_tuple = (1, (2, 3), 4)
inner_element = nested_tuple[1][0]  # 2

### Tuple Immutability
- Tuples are immutable, meaning their contents cannot be changed after creation.

In [ ]:
numbers = (1, 2, 3)
# Attempting to change an element will raise an error
# numbers[0] = 10  # TypeError: 'tuple' object does not support item assignment

While you cannot change elements, you can concatenate or multiply tuples to create new tuples.

In [ ]:
# Concatenation
tuple1 = (1, 2)
tuple2 = (3, 4)
combined = tuple1 + tuple2  # (1, 2, 3, 4)

# Repetition
repeated = tuple1 * 3  # (1, 2, 1, 2, 1, 2)
combined
repeated

(1, 2, 1, 2, 1, 2)

### Tuple Methods
Tuples have limited built-in methods compared to lists due to their immutability.

count(item): Returns the number of times an item appears.

In [ ]:
numbers = (1, 2, 2, 3)
count_of_twos = numbers.count(2)  # 2

# index(item, start, end): Returns the index of the first occurrence of an item.
position = numbers.index(2)  # 1

### Iterating Over Tuples
You can iterate over tuples using loops.

In [ ]:
fruits = ('apple', 'banana', 'cherry')

# Using a for loop
for fruit in fruits:
    print(fruit)

# Using indices
for i in range(len(fruits)):
    print(fruits[i])

# Using enumerate to get index and value
for index, fruit in enumerate(fruits):
    print(index, fruit)

apple
banana
cherry
apple
banana
cherry
0 apple
1 banana
2 cherry

## 13. Python Sets

A **set** is an **unordered**, **mutable** collection of **unique** items (no duplicates).

### Key points
- **Unordered**: no indexing or slicing.
- **Unique elements**: duplicates are removed automatically.
- **Mutable**: you can add/remove items.
- **Fast membership tests**: `x in s` is O(1) on average.
- **Hashable only**: elements must be immutable/hashable (e.g., numbers, strings, tuples).

In [ ]:
my_set = {"apple", "banana", "cherry", "apple"}
print(my_set)

{'apple', 'banana', 'cherry'}

In [ ]:
fruits = {"apple", "banana", "cherry"}

fruits.add("orange")       # add one item
fruits.remove("banana")    # remove an item; error if not found

item = fruits.pop()        # removes and returns a random item
print("Popped item:", item)

print("Set now:", fruits)
print("Size:", len(fruits))

fruits.clear()             # remove all items
print("After clear:", fruits)

Popped item: apple
Set now: {'orange', 'cherry'}
Size: 2
After clear: set()

---

<a id="14"></a>
## 14. Python Dictionaries

- In Python, a dictionary is a built-in data type that represents an unordered, mutable collection of key-value pairs.
-  Dictionaries are also known as associative arrays or hash maps in other programming languages.
-  They allow you to store and retrieve data efficiently based on unique keys.

### Creating Dictionaries
- Dictionaries can be created using curly braces `{}` with key-value pairs separated by colons `:`.

In [ ]:
# Empty dictionary
empty_dict = {}

# Dictionary with string keys
person = {
    'name': 'Alice',
    'age': 30,
    'city': 'New York'
}

# Dictionary with mixed key types
employee = {
    101: 'John Doe',
    102: 'Jane Smith',
    103: 'Emily Davis'
}

# Using the dict() constructor
person = dict(name='Bob', age=25, city='Los Angeles')

# Creating a dictionary from a list of tuples
items = [('name', 'Charlie'), ('age', 28)]
person = dict(items)

### Accessing Dictionary Elements
You can access dictionary values by referencing their keys using square brackets `[]` or the `get()` method.

In [ ]:
person = {'name': 'Alice', 'age': 30, 'city': 'New York'}

# Using square brackets
name = person['name']       # 'Alice'

# Using get() method
age = person.get('age')     # 30

### Modifying Dictionaries
Dictionaries are `mutable`, allowing you to add, update, or remove key-value pairs.
### Adding Elements

In [ ]:
person = {'name': 'Alice', 'age': 30}

# Adding a new key-value pair
person['city'] = 'New York'
# person = {'name': 'Alice', 'age': 30, 'city': 'New York'}

# Updating an existing key
person['age'] = 31
# person = {'name': 'Alice', 'age': 31, 'city': 'New York'}

# Removing elements

age = person.pop('age')  # 31
# person = {'name': 'Alice', 'city': 'New York'}

# del statement: Deletes a key-value pair
del person['name']
# person = {'city': 'New York'}

# clear(): Removes all items from the dictionary
person.clear()
# person = {}

### Dictionary Methods
`keys()`: Returns a view object of all keys.

In [ ]:
person = {'name': 'Alice', 'age': 30}

keys = person.keys()  # dict_keys(['name', 'age', 'city'])
keys

dict_keys(['name', 'age'])

`values()`: Returns a view object of all values.

In [ ]:
values = person.values()  # dict_values(['Alice', 30, 'New York'])

`items()`: Returns a view object of key-value pairs as tuples.

In [ ]:
items = person.items()  # dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York')])

### Iterating Over Dictionaries
You can iterate over keys, values, or key-value pairs.

In [ ]:
person = {'name': 'Alice', 'age': 30, 'city': 'New York'}

# Iterating over keys
for key in person:
    print(key)

# Iterating over values
for value in person.values():
    print(value)

# Iterating over key-value pairs
for key, value in person.items():
    print(f"{key}: {value}")

---

<a id="16"></a>
## 16. Python While Loops

Loops allow you to execute code multiple times.
The basic syntax of a while loop in Python is:

In [ ]:
while condition:
    # Code block to execute

-condition: A Boolean expression that is evaluated before each iteration. If the condition is True, the loop continues; if it is False, the loop exits.
- Code Block: The indented block of code that will execute repeatedly as long as the condition is True.

In [ ]:
i = 1
while i < 6:
    print(i)
    i += 1

1
2
3
4
5

## break and continue Statements
### break Statement
The break statement terminates the loop entirely and transfers execution to the statement immediately following the loop

In [ ]:
count = 0
while True:
    print("Count is:", count)
    count += 1
    if count >= 5:
        break  # Exit the loop

Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4

## continue Statement
The continue statement skips the rest of the code inside the loop for the current iteration and moves to the next iteration.

In [ ]:
count = 0
while count < 5:
    count += 1
    if count == 3:
        continue  # Skip the rest of the loop when count is 3
    print("Count is:", count)

Count is: 1
Count is: 2
Count is: 4
Count is: 5

### Using else with while Loops
- An optional else clause can be added to a while loop. The else block executes when the loop condition becomes False naturally, but not when the loop is terminated by a break statement.

In [ ]:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
else:
    print("Loop has ended.")

---


## Python Functions

- In Python, functions are reusable blocks of code that perform a specific task.
- They help in making code modular, organized, and efficient by reducing repetition.
- Functions can take inputs, process them, and return outputs.

## Defining Functions
- A function is defined using the def keyword, followed by the function name and parentheses () which may include parameters.
- The function body starts with a colon : and is indented.

In [ ]:
def function_name(parameters):
    # Function body
    ...

### Basic Function Syntax

In [ ]:
def greet():
    print("Hello, World!")

# Calling the function
greet()

Hello, World!

### Function with Parameters

In [ ]:
def greet(name):
    print(f"Hello, {name}!")

greet("Alice")

Hello, Alice!

### Function Parameters and Arguments
#### Positional Arguments
Arguments passed to a function based on their position.

In [ ]:
def add(a, b):
    return a + b

result = add(5, 3)
print(result)  # Output: 8

### Keyword Arguments
Arguments passed to a function using parameter names as keywords.

In [ ]:
def subtract(a, b):
    return a - b

result = subtract(b=5, a=10)
print(result)  # Output: 5

### Default Arguments
 - Parameters with default values, which are used if no argument is provided.

In [ ]:
def power(base, exponent=2):
    return base ** exponent

print(power(5))       # Output: 25 (uses default exponent 2)
print(power(5, 3))    # Output: 125

*args **(Non-Keyword Variable Arguments)**
- Allows a function to accept any number of positional arguments as a tuple.

In [ ]:
def multiply(*args):
    result = 1
    for num in args:
        result *= num
    return result

print(multiply(2, 3))          # Output: 6
print(multiply(2, 3, 4))       # Output: 24

### Scope of Variables
- Local Scope: Variables defined within a function are local to that function.
- Global Scope: Variables defined outside any function are global.

In [ ]:
x = "global"

def my_function():
    x = "local"
    print("Inside function:", x)

my_function()
print("Outside function:", x)

Inside function: local
Outside function: global

### Using global Keyword
-If you need to modify a global variable inside a function, use the global keyword.

In [ ]:
count = 0

def increment():
    global count
    count += 1

increment()
print(count)  # Output: 1

1

# Class Exercise

---

##  Python Classes/Objects

- Object-Oriented Programming (OOP) is a programming paradigm based on the concept of "objects", which can contain data and code: data in the form of fields (attributes or properties), and code in the form of procedures (methods).

Key Concepts:
- **Class**: A blueprint or template for creating objects.
- **Object**: An instance of a class.

### Classes and Objects in Python
- In Python, everything is an object, and classes define the structure and behavior of these objects.

- **Class**: Defines a new data type.
- **Object**: An instance of a class with actual values.

### Defining a class
- You can define a class using the `class` keyword.

In [ ]:
class Robot:
    pass  # An empty class

Example:

In [ ]:
class Robot:
    def __init__(self, name):
        self.name = name

- `__init__` is a special method called a constructor.
- `self` refers to the instance of the class.

### Creating Objects (Instances)
- You create an object by calling the class as if it were a function.

In [ ]:
robot1 = Robot("R2-D2")
robot2 = Robot("C-3PO")

### Instance Attributes and Methods
#### Instance Attributes
Attributes that are specific to each object.

In [ ]:
class Robot:
    def __init__(self, name):
        self.name = name  # Instance attribute

### Instance Methods
- Functions defined within a class that operate on instances of that class.

In [ ]:
class Robot:
    def __init__(self, name):
        self.name = name

    def introduce(self):
        return f"Hello, my name is {self.name}."

### Using Instance Methods

In [ ]:
robot = Robot("HAL 9000")
print(robot.introduce())  # Output: Hello, my name is HAL 9000.

## Class Attributes
- Attributes that are shared among all instances of a class.

In [ ]:
class Robot:
    population = 0  # Class attribute

    def __init__(self, name):
        self.name = name
        Robot.population += 1

### Accessing Class Attributes

In [ ]:
print(Robot.population)  # Accessing via class
print(robot.population)  # Accessing via instance

### Encapsulation and Access Modifiers
#### Encapsulation
- The bundling of data (attributes) and methods that operate on that data within one unit, e.g., a class.

  #### Access Modifiers in Python
- `Public`: Accessible from anywhere (`self.name`)
- `Protected`: Conventionally indicated with a single underscore (`self._name`)
- `Private`: Conventionally indicated with a double underscore (`self.__name`)
- Note: Python does not enforce access restrictions but relies on naming conventions.

In [ ]:
class Data:
    def __init__(self):
        self.public = "I am public"
        self._protected = "I am protected"
        self.__private = "I am private"

    def get_private(self):
        return self.__private

---


##  Python Modules

- A module is a file containing Python definitions and statements intended for use in other Python programs.
-Modules help organize code into manageable sections and promote code reusability.
### Why Use Modules?
- Organization: Break down complex programs into smaller, manageable, and organized files.
- Reusability: Reuse functions, classes, and variables across multiple programs.

### Creating a Module
- Any Python file (`.py` extension) can be considered a module.
- Example: Create a file named `math_utils.py`.

In [ ]:
# math_utils.py

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

### Using a Module
- Import the module into another script using the import statement.

In [ ]:
# main.py

import math_utils

result = math_utils.add(5, 3)
print(result)  # Output: 8

### Exploring Built-in Modules
- Python comes with a standard library of built-in modules.
### Common Built-in Modules
- `math`: Provides mathematical functions.
- `datetime`: Supplies classes for manipulating dates and times.
- `random`: Generates pseudo-random numbers.
- `os`: Provides functions for interacting with the operating system.
- `sys`: Accesses system-specific parameters and functions.

In [ ]:
import datetime

now = datetime.datetime.now()
print(now)

2026-03-17 10:06:50.211767

In [ ]:
import math

print(math.sqrt(16))   # Output: 4.0
print(math.pi)         # Output: 3.141592653589793

### The from...import Statement
- Allows you to import specific attributes from a module or package.
### Syntax
from module_name import attribute_name

### Example

In [ ]:
from math import pi, sqrt

print(pi)           # Output: 3.141592653589793
print(sqrt(25))     # Output: 5.0

3.141592653589793
5.0

### Aliasing Modules
- You can provide an alias for a module or attribute using the as keyword.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])

# NumPy
- **NumPy** stands for Numerical Python.
- It is a fundamental package for scientific computing in Python.
- Provides support for large, multi-dimensional arrays and matrices.
- Offers a collection of mathematical functions to operate on these arrays efficiently.

# Why Use NumPy?
- **Performance**: NumPy arrays are more compact and faster than Python lists.
- **Convenience**: Provides a wide range of array operations for mathematical computations.
- **Interoperability**: Works well with other libraries like SciPy, Pandas, Matplotlib, etc.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

## Installing NumPy

 ### Using pip

In [ ]:
pip install numpy

#### Using Conda

In [ ]:
conda install numpy

### NumPy Arrays

- The core of NumPy is the `ndarray` (n-dimensional array) object.
 - An ndarray is a homogeneous collection of elements indexed by non-negative integers.

In [ ]:
import numpy as np

# One-dimensional array
a = np.array([1, 2, 3])
print(a)  # Output: [1 2 3]

# Two-dimensional array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
# Output:
# [[1 2 3]
#  [4 5 6]]

[1 2 3]
[[1 2 3]
 [4 5 6]]

#### Using Built-in Functions

- `np.zeros(shape)`: Create an array filled with zeros.
- `np.ones(shape)`: Create an array filled with ones.
- `np.full(shape, fill_value)`: Create an array filled with a constant value.
- `np.eye(N)`: Create an identity matrix.
- `np.arange(start, stop, step)`: Create an array with evenly spaced values.

In [ ]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3,2))
full_array = np.full((2, 3), 5)
identity_matrix = np.eye(3)
range_array = np.arange(0, 10, 3)
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

##  Array Attributes
- The shape of an array is the number of elements in each dimension.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

arr.shape

(2, 4)

In [ ]:
arr3 = np.array([[[1, 2],
                  [3, 4]],
                 [[5, 6],
                  [7, 8]]])
print("\nArray:\n", arr3)
print("Dimension (ndim):", arr3.ndim)  # Output: 3
print("Shape:", arr3.shape)            # Output: (2, 2, 2)

Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension (ndim): 3
Shape: (2, 2, 2)

### Basic Array Operations
- Operations are applied element-wise.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)       # Output: [5 7 9]
print(a - b)       # Output: [-3 -3 -3]
print(a * b)       # Output: [4 10 18]
print(a / b)       # Output: [0.25 0.4 0.5]
print(a ** 2)      # Output: [1 4 9]

## Mathematical Functions
### Aggregation Functions
- Operate over an entire array or along an axis.

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

print(a.sum())          # Output: 10
print(a.sum(axis=0))    # Output: [4 6]
print(a.sum(axis=1))    # Output: [3 7]

### Statistical Functions

In [ ]:
print(a.mean())         # Output: 2.5
print(a.std())          # Standard deviation
print(a.min())          # Minimum value
print(a.max())          # Maximum value
print(a.argmin())       # Index of minimum value
print(a.argmax())       # Index of maximum value

2.0
0.816496580927726
1
3
0
2

# Pandas
- Pandas is an open-source Python library providing high-performance, easy-to-use data structures, and data analysis tools.
- Pandas allows us to analyze big data and make conclusions based on statistical theories.

- Pandas can clean messy data sets, and make them readable and relevant.
In works  well with other popular Python data science packages such as:

- NumPy for numerical computing
- Matplotlib, Seaborn, Plotly, and other data visualization packages
- scikit-learn for machine learning
### Installation

In [ ]:
pip install pandas

In [ ]:
conda install pandas

In [ ]:
import pandas as pd

print(pd.__version__)

2.2.2

## Pandas Data Structures
## Series
- A Series is a one-dimensional labeled array capable of holding any data type.
- A Pandas Series is like a column in a table.

In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

In [ ]:
import pandas as pd

# From a list
s = pd.Series([1, 3, 5, 7, 9])

# From a dictionary
s = pd.Series({'a': 1, 'b': 2, 'c': 3})

### Indexing and slicing

In [ ]:
# Access by position

#s[2] # deprecated
s.iloc[0]

# Access by label
#s['a']

# Slicing
#s[1:3]

1

## DataFrame
- A DataFrame is a two-dimensional labeled data structure with columns of potentially different types.
- Series is like a column, a DataFrame is the whole table.

#### Creating a DataFrame

In [ ]:
# From a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
emp = pd.DataFrame(data)
emp

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

###  Viewing Data

In [ ]:
df.head(10)      # First 5 rows
df.tail(3)     # Last 3 rows
df.info()      # Summary of the DataFrame
df.describe()  # Statistical summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

### Selection and Indexing

In [ ]:
# Selecting columns
df['Name']

# Selecting multiple columns
df[['Name', 'Salary']]

# Selecting rows by label (requires setting index)
df.loc[0]

# Selecting rows by position
df.iloc[0]

Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object

### **Key Differences**:

| Feature         | `.loc`                         | `.iloc`                           |
| --------------- | ------------------------------ | --------------------------------- |
| Selection Type  | Label-based                    | Integer-based                     |
| Indexes         | Uses row and column **labels** | Uses row and column **positions** |
| Slicing         | **Inclusive** of the end label | **Exclusive** of the end position |
| Condition-based | Can use boolean conditions     | Does not support conditions       |

### Adding/Deleting Columns

In [ ]:
# Adding a new column
df['Bonus'] = df['Salary'

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,3865168.5
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,3398058.5
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,574320.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2500000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,1216666.5
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,450000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,1450000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,473638.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

# Deleting a column
del df['Bonus']

### Handling Missing Data

In [ ]:
# Detecting missing values
df.isnull()

# Dropping missing values
df.dropna()

# Filling missing values
df.fillna(value=0)

### Data Input and Output
Pandas can read and write data from/to various file formats.

In [ ]:
# CSV
import pandas as pd


df = pd.read_csv('data.csv')

# Excel
df = pd.read_excel('data.xlsx', sheet_name='Sheet1')

# JSON
df = pd.read_json('data.json')

In [ ]:
import pandas as pd
df=pd.read_csv("gdp.csv")
df.head(10)

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,4797.295051,5288.040382,6223.367465
1,Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,2277.140884,2773.287312,4797.231267
2,Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,1232.975292,1372.877931,1441.284873
3,Botswana,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,8647.142313,11003.605080,12569.851770
4,Burkina Faso,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,946.294962,1037.645221,1217.032994
5,Burundi,339.296459,379.564628,355.203227,412.977514,464.099504,556.103265,559.603231,621.818819,631.699878,463.115148,446.403513,430.070692
6,Cameroon,1172.667655,1313.048099,1399.607441,1508.453148,1684.146528,1783.432873,2367.983282,2602.664206,1793.163278,1694.337469,1934.011449,2042.095240
7,Central African Republic,1071.310713,1190.844328,1193.068753,1136.056615,1070.013275,1109.374338,956.752991,844.876350,747.905525,740.506332,738.690607,706.016537
8,Chad,1178.665927,1308.495577,1389.817618,1196.810565,1104.103987,1133.984950,797.908101,952.386129,1058.064300,1004.961353,1156.181860,1704.063724
9,Comoros,1102.990936,1211.148548,1406.648278,1876.029643,1937.577675,1172.603047,1267.100083,1315.980812,1246.907370,1173.618235,1075.811558,986.147879

In [ ]:
##Get basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         52 non-null     object
 1   gdpPercap_1952  52 non-null     float64
 2   gdpPercap_1957  52 non-null     float64
 3   gdpPercap_1962  52 non-null     float64
 4   gdpPercap_1967  52 non-null     float64
 5   gdpPercap_1972  52 non-null     float64
 6   gdpPercap_1977  52 non-null     float64
 7   gdpPercap_1982  52 non-null     float64
 8   gdpPercap_1987  52 non-null     float64
 9   gdpPercap_1992  52 non-null     float64
 10  gdpPercap_1997  52 non-null     float64
 11  gdpPercap_2002  52 non-null     float64
 12  gdpPercap_2007  52 non-null     float64
dtypes: float64(12), object(1)
memory usage: 5.4+ KB

In [ ]:
#This provides statistical measures like mean, standard deviation, min, max, etc. for numerical columns.
df.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,1252.572466,1385.236062,1598.078825,2050.363801,2339.615674,2585.938508,2481.592960,2282.668991,2281.810333,2378.759555,2599.385159,3089.032605
std,982.952116,1134.508918,1461.839189,2847.717603,3286.853884,4142.398707,3242.632753,2566.531947,2644.075602,2820.728117,2972.651308,3618.163491
min,298.846212,335.997115,355.203227,412.977514,464.099504,502.319733,462.211415,389.876185,410.896824,312.188423,241.165876,277.551859
25%,534.990554,606.954355,673.329046,779.815648,815.919804,805.612125,828.656854,764.598759,743.908497,791.901966,780.577824,862.951537
50%,987.025569,1024.022987,1133.783678,1210.376379,1443.372508,1399.638836,1323.728306,1219.585563,1161.631357,1179.883114,1215.683217,1452.267078
75%,1454.886645,1573.040442,1702.219247,1890.112274,2292.258613,2841.282025,2787.582271,2786.310885,2707.896077,2856.386031,3314.887180,3993.501583
max,4725.295531,5487.104219,6757.030816,18772.751690,21011.497210,21951.211760,17364.275380,11864.408440,13522.157520,14722.841880,12521.713920,13206.484520

In [ ]:
gambia_data = df[df['country'] == 'Gambia']
gambia_mean_gdp = gambia_data.iloc[:, 1:].mean()
print("\nMean GDP per capita for Gambia across all years:")
print(gambia_mean_gdp)

Mean GDP per capita for Gambia across all years:
gdpPercap_1952    485.230659
gdpPercap_1957    520.926711
gdpPercap_1962    599.650276
gdpPercap_1967    734.782912
gdpPercap_1972    756.086836
gdpPercap_1977    884.755251
gdpPercap_1982    835.809611
gdpPercap_1987    611.658861
gdpPercap_1992    665.624413
gdpPercap_1997    653.730170
gdpPercap_2002    660.585600
gdpPercap_2007    752.749726
dtype: float64

In [ ]:
# mean across all years
gambia_overall_mean = gambia_mean_gdp.mean()
print(f"\nOverall mean GDP per capita for Gambia: {gambia_overall_mean:.2f}")

Overall mean GDP per capita for Gambia: 680.13

### Grouby
- The groupby command in pandas is very useful for aggregating data and performing operations on groups.
- It makes the task of splitting the Dataframe over some criteria really easy and efficient.

In [ ]:
import pandas as pd
nba = pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

- fill missing values with zero

In [ ]:
#Calculate the growth rate between 1952 and 2007 for each country:

cleannba = nba.fillna(value=0)
cleannba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [ ]:
## Average age in each team
average = cleannba.groupby("Team")["Age"].mean().round().astype(int)
average

Team
0                          0
Atlanta Hawks             28
Boston Celtics            25
Brooklyn Nets             26
Charlotte Hornets         26
Chicago Bulls             27
Cleveland Cavaliers       30
Dallas Mavericks          30
Denver Nuggets            26
Detroit Pistons           26
Golden State Warriors     28
Houston Rockets           27
Indiana Pacers            26
Los Angeles Clippers      29
Los Angeles Lakers        28
Memphis Grizzlies         28
Miami Heat                29
Milwaukee Bucks           25
Minnesota Timberwolves    26
New Orleans Pelicans      27
New York Knicks           27
Oklahoma City Thunder     27
Orlando Magic             25
Philadelphia 76ers        25
Phoenix Suns              26
Portland Trail Blazers    25
Sacramento Kings          27
San Antonio Spurs         32
Toronto Raptors           26
Utah Jazz                 24
Washington Wizards        28
Name: Age, dtype: int64

In [ ]:
# number of players in each team
player_counts = cleannba.groupby("Team")["Name"].count()
player_counts

Team
0                          1
Atlanta Hawks             15
Boston Celtics            15
Brooklyn Nets             15
Charlotte Hornets         15
Chicago Bulls             15
Cleveland Cavaliers       15
Dallas Mavericks          15
Denver Nuggets            15
Detroit Pistons           15
Golden State Warriors     15
Houston Rockets           15
Indiana Pacers            15
Los Angeles Clippers      15
Los Angeles Lakers        15
Memphis Grizzlies         18
Miami Heat                15
Milwaukee Bucks           16
Minnesota Timberwolves    14
New Orleans Pelicans      19
New York Knicks           16
Oklahoma City Thunder     15
Orlando Magic             14
Philadelphia 76ers        15
Phoenix Suns              15
Portland Trail Blazers    15
Sacramento Kings          15
San Antonio Spurs         15
Toronto Raptors           15
Utah Jazz                 15
Washington Wizards        15
Name: Name, dtype: int64

In [ ]:
#Total salary per team
team_salary = cleannba.groupby("Team")["Salary"].sum()
team_salary

Team
0                                 0.0
Atlanta Hawks              72902950.0
Boston Celtics             58541068.0
Brooklyn Nets              52528475.0
Charlotte Hornets          78340920.0
Chicago Bulls              86783378.0
Cleveland Cavaliers       106988689.0
Dallas Mavericks           71198732.0
Denver Nuggets             60121930.0
Detroit Pistons            67168263.0
Golden State Warriors      88868997.0
Houston Rockets            75283021.0
Indiana Pacers             66751826.0
Los Angeles Clippers       94854640.0
Los Angeles Lakers         71770431.0
Memphis Grizzlies          76550880.0
Miami Heat                 82515673.0
Milwaukee Bucks            69603517.0
Minnesota Timberwolves     59709697.0
New Orleans Pelicans       82750774.0
New York Knicks            73303898.0
Oklahoma City Thunder      93765298.0
Orlando Magic              60161470.0
Philadelphia 76ers         30992894.0
Phoenix Suns               63445135.0
Portland Trail Blazers     48301818.0
Sacramento Kings           71683666.0
San Antonio Spurs          84442733.0
Toronto Raptors            71117611.0
Utah Jazz                  63060091.0
Washington Wizards         76328636.0
Name: Salary, dtype: float64

In [ ]:
team_salary = cleannba.groupby("Team")["Salary"].sum().sort_values(ascending=False)
team_salary

Team
Cleveland Cavaliers       106988689.0
Los Angeles Clippers       94854640.0
Oklahoma City Thunder      93765298.0
Golden State Warriors      88868997.0
Chicago Bulls              86783378.0
San Antonio Spurs          84442733.0
New Orleans Pelicans       82750774.0
Miami Heat                 82515673.0
Charlotte Hornets          78340920.0
Memphis Grizzlies          76550880.0
Washington Wizards         76328636.0
Houston Rockets            75283021.0
New York Knicks            73303898.0
Atlanta Hawks              72902950.0
Los Angeles Lakers         71770431.0
Sacramento Kings           71683666.0
Dallas Mavericks           71198732.0
Toronto Raptors            71117611.0
Milwaukee Bucks            69603517.0
Detroit Pistons            67168263.0
Indiana Pacers             66751826.0
Phoenix Suns               63445135.0
Utah Jazz                  63060091.0
Orlando Magic              60161470.0
Denver Nuggets             60121930.0
Minnesota Timberwolves     59709697.0
Boston Celtics             58541068.0
Brooklyn Nets              52528475.0
Portland Trail Blazers     48301818.0
Philadelphia 76ers         30992894.0
0                                 0.0
Name: Salary, dtype: float64

## Writing to data

In [ ]:
# To CSV
team_salary.to_csv('teamsalary.csv', index=False)

# To Excel
df.to_excel('output.xlsx', sheet_name='Sheet1')

# To JSON
df.to_json('output.json')